version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: companion_postgres
    environment:
      POSTGRES_USER: test_db
      POSTGRES_DB: test
      POSTGRES_PASSWORD: test
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - mc_network

  mcp-server:
    build: .
    container_name: company_mcp_server
    environment:
      - DB_HOST: localhost
      - DB_PORT: 5432
      - DB_USER: test
      - DB_PASSWORD: test
      - DB_DATABASE: test_db
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        - postgres
    networks:
      - mcp_network

networks:
  mcp_network:
    driver: bridge

volumes:
  postgres_data:
